### ISSUE TITLE
Installation issues.

### ISSUE THREAD

**Issue by pooyasa** [mtkarimi/persian-license-plate-recognition#2]
Hi!

Currently found 2 issues.
1. botocore==1.34.45 depends on another version of urllib3 so I had to remove the required urllib3 version from requirements.txt file
2. yolov5 is a submodule and need to be cloned using --recursive however the [repository](https://github.com/mtkarimi/smart-resident-guard/blob/main/yolov5) does not exist.
Also, with this much dependencies, it is much better to start a venv in the beginning.
Many thanks for your work.

**Comment by pooyasa** [comment]
Sure. Also by default, main_yolo reads from a file which does not exist. Settings button does not work so you need to change config.ini or line 361 to `self.Capture = cv2.VideoCapture(0)` to read from the webcam.

Also, any way to increase the performance by pruning or quantizing the model?

**Comment by milad-fa** [comment]
```
C:\Users\Fatemeh\Desktop\pelak>C:\Users\Fatemeh\AppData\Local\Programs\Python\Python311\python.exe C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\home-yolo.py
Traceback (most recent call last):
  File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\home-yolo.py", line 32, in <module>
    from database.db_entries_utils import db_entries_time, dbGetAllEntries
  File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\database\db_entries_utils.py", line 6, in <module>
    from database.classEntries import Entries
  File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\database\classEntries.py", line 5, in <module>
    from helper.gui_maker import get_status_color, get_status_text
  File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\helper\gui_maker.py", line 14, in <module>
    from helper.text_decorators import *
  File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\helper\text_decorators.py", line 14, in <module>
    params = Parameters()
             ^^^^^^^^^^^^
  File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\configParams.py", line 33, in __init__
    dbconfig = config_object["DATABASE"]
               ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Fatemeh\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'DATABASE'
```


Hello, I am encountering this error while running. Could you please guide me? Thank you

**Comment by mtkarimi** [comment]
i updated to core, please clone and let me know

**Comment by aminallahrabi** [comment]
> ```
> C:\Users\Fatemeh\Desktop\pelak>C:\Users\Fatemeh\AppData\Local\Programs\Python\Python311\python.exe C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\home-yolo.py
> Traceback (most recent call last):
>   File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\home-yolo.py", line 32, in <module>
>     from database.db_entries_utils import db_entries_time, dbGetAllEntries
>   File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\database\db_entries_utils.py", line 6, in <module>
>     from database.classEntries import Entries
>   File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\database\classEntries.py", line 5, in <module>
>     from helper.gui_maker import get_status_color, get_status_text
>   File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\helper\gui_maker.py", line 14, in <module>
>     from helper.text_decorators import *
>   File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\helper\text_decorators.py", line 14, in <module>
>     params = Parameters()
>              ^^^^^^^^^^^^
>   File "C:\Users\Fatemeh\Desktop\pelak\smart-resident-guard\configParams.py", line 33, in __init__
>     dbconfig = config_object["DATABASE"]
>                ~~~~~~~~~~~~~^^^^^^^^^^^^
>   File "C:\Users\Fatemeh\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 979, in __getitem__
>     raise KeyError(key)
> KeyError: 'DATABASE'
> ```
> 
> Hello, I am encountering this error while running. Could you please guide me? Thank you

i have the sam error when i run code in colab.:
Traceback (most recent call last):
  File "/content/drive/MyDrive/persian-license-plate-recognition/home-yolo.py", line 32, in <module>
    from database.db_entries_utils import db_entries_time, dbGetAllEntries
  File "/content/drive/MyDrive/persian-license-plate-recognition/database/db_entries_utils.py", line 6, in <module>
    from database.classEntries import Entries
  File "/content/drive/MyDrive/persian-license-plate-recognition/database/classEntries.py", line 5, in <module>
    from helper.gui_maker import get_status_color, get_status_text
  File "/content/drive/MyDrive/persian-license-plate-recognition/helper/gui_maker.py", line 14, in <module>
    from helper.text_decorators import *
  File "/content/drive/MyDrive/persian-license-plate-recognition/helper/text_decorators.py", line 14, in <module>
    params = Parameters()
  File "/content/drive/MyDrive/persian-license-plate-recognition/configParams.py", line 33, in __init__
    dbconfig = config_object["DATABASE"]
  File "/usr/lib/python3.10/configparser.py", line 965, in __getitem__
    raise KeyError(key)
KeyError: 'DATABASE'
